### ISSUE TITLE
Custom conditions not showing up in django admin dropdown

### ISSUE THREAD

**Issue by callorico** [cfpb/django-flags#5] opened 2018-08-27 03:51 UTC
I'm creating a custom condition function and decorating it with `@register` in a separate Django app. However, I do not see it showing up in the condition dropdown in the django admin. It seems like this is because the condition choices are set when the form module is loaded. This happens fairly early when the model admin is registered. I've tried to address that here https://github.com/cfpb/django-flags/pull/4 but please let me know if there is different pattern I should be following to register custom conditions.

**Comment by willbarton** [comment] 2018-08-27 21:44
@callorico Nope, I can confirm, it looks like you've caught a bug! I'll make sure to look over #4.

**Comment by willbarton** [comment] 2018-08-29 19:48
Merged #4, which fixes this issue.

**Closed by willbarton** 2018-08-29 19:48 UTC
